#ifndef NAMMA_AUTOSAR_DIO_CFG_H
#define NAMMA_AUTOSAR_DIO_CFG_H

// This file is autogenerated, any hand modifications will be lost!

#include <Dio.h>
#include <Port_cfg.h>


extern Dio_ChannelType DioChan2PortLookup[MAX_PORT_ID+1];



#endif
